### ISSUE TITLE
Error Home Assistant Configuration check resulted in an error: undefined

### ISSUE THREAD

**Issue by angeltonio** [keesschollaart81/vscode-home-assistant#393]
Extension runs in:
- [x] VS Code for Desktop 
- [] Hassio Add-on 
- [ ] Visual Studio Online
- [ ] Other: 

I'm running VS Code on:
- [ x] Windows 
- [] Mac 
- [] Linux 

I'm accessing my files:
- [] From local disk 
- [ ] Via remote SSH 
- [x] Smb
- [ ] Other:  

But the connection is established correctly, I can reload the scripts normally.

**Comment by calexandre** [comment]
I have the same issue. Started happening after upgrading VSCode...

**Comment by apaperclip** [comment]
> I have the same issue.
> Currently running on WSL1.
> Started happening after upgrading VSCode...
> 
> EDIT: Just rolled back to version 1.6.5 and it works. I guess this has something to do with the latest version 1.7.x

Same here too.  vsocde on windows to a docker ha instance.

**Comment by frenck** [comment]
Confirmed and reproducible on my end as well.

**Comment by frenck** [comment]
Fixed in #411

**Comment by whizkid79** [comment]
This is also happening to me, running as
[x] Hassio Add-on
[x] Visual Studio Online

Version is 1.12.0
VSCode version is 2.9.0

**Comment by frenck** [comment]
@whizkid79 That cannot be the exact same issue, as the code that caused this issue isn't fixed but replaced entirely.

Could you raise a new issue and provide as many details as possible? Preferably, with a re-production scenario.

Thanks 👍

**Comment by genem2** [comment]
Started seeing this recently; trimmed my configuration.yaml down to the min, and still getting it.  Anyone else?

## @ext:keesschollaart.vscode-home-assistant  
**v1.21.0**

## Visual Studio Code:

Version: 1.60.2 (user setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

## Home Assistant

version | core-2021.9.7
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.28-Unraid
arch | x86_64
timezone | America/Los_Angeles
