### ISSUE TITLE
Error connecting to your Home Assistant Server

### ISSUE THREAD

**Issue by naamah75** [keesschollaart81/vscode-home-assistant#7]
Installed extension, configured with server address (I'm sure that the address is correct cause I've tested on browser) and with long live token, then restarted VScode but I get this error:

`Error connecting to your Home Assistant Server at https://192.168.1.65:8123, check your network or update your VS Code Settings. Error: 1`

VScode:
```
Versione: 1.32.3 (user setup)
Commit: a3db5be9b5c6ba46bb7555ec5d60178ecc2eaae4
Data: 2019-03-14T23:43:35.476Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```

**Comment by maxandersen** [comment]
same here - I even notice that it seems to use old values/settings in the error as if settings are not applied when saved.

**Comment by keesschollaart81** [comment]
I've done a couple of things to get this better. 
- The error now does not give a number ('1') but a text (in this case 'ERR_CANNOT_CONNECT')
- The error message now includes a the first couple of characters of the token used 
- The settings are from now on by default applied on user-level instead of workspace level (this can still be overridden via the UI or a .vscode/.settings file)
- After updating the settings, the active connection is reset/disconnected and and the new settings will be used. So VS Code does not need a restart any more

Let me know if this is still an issue for you!

**Comment by naamah75** [comment]
Just updated, now I've the following description:

`Error connecting to your Home Assistant Server at https://192.168.1.65:8123 and token 'eyJ0e...', check your network or update your VS Code Settings, make sure to (also) check your workspace settings! Error: ERR_CANNOT_CONNECT`

**Comment by keesschollaart81** [comment]
Are you able to run the [demo app](https://hass-auth-demo.glitch.me/) from the underlying [home-assistant-js-websocket](https://github.com/home-assistant/home-assistant-js-websocket) library from the same machine?

**Comment by naamah75** [comment]
yes, it works! I got a list of all my entities.

**Comment by keesschollaart81** [comment]
That's good and bad news.. :-) I have no clue! Uninstall / install the extension maybe?

**Comment by naamah75** [comment]
Already unistalled/reinstalled with no luck... maybe some authorization issue? how I can test it?

**Comment by lexitus** [comment]
I have what I suspect is the same issue - same symptoms anyway. I've also tried the demo app linked above, with success. I wondered if it might be a certificate problem - since we are both using https. 

Running VS Code with --ignore-certificate-errors --verbose still produces the ERR_CANNOT_CONNECT for me - relevant output attached.

![image](https://user-images.githubusercontent.com/38081592/54839944-2d62cd80-4ccc-11e9-8e92-b9b9640b21c5.png)

**Comment by keesschollaart81** [comment]
Ah, that's a great catch. Indeed when you try to connect over HTTPS and you have a certificate problem, it does not connect. Not that I have reproduced it, I'll try to find a solution in the coming days. To be continued... Thanks @lexitus!

**Comment by naamah75** [comment]
I'had the same suspect of @lexitus, but I'm not able to prove. Great job @lexitus and thanks to your support @keesschollaart81

**Comment by maxandersen** [comment]
just want to confirm that using https://localhost:8123 fails, http://localhost:8123 succeeds. so yeah, something wonky about certificates and/or https as https://localhost:8123 should "just" work :)

**Comment by dpackham** [comment]
I am using HTTP and am getting this error.  

Error connecting to your Home Assistant Server at http://10.1.1.26:8123 and token 'eyJ0e...', check your network or update your VS Code Settings, make sure to (also) check your workspace settings! Error: ERR_INVALID_AUTH

**Comment by carstenschroeder** [comment]
I have the same issue and I am also using ssl. What I do not get is, that I have a valid certificate (COMODO RSA) for the HA- URL. Also Chrome takes it for valid. Why does VS Code take it for invalid? Can somebody give me a hint how to analyse this?

**Comment by keesschollaart81** [comment]
As you can see, two messages above, there's a reference to a PR to the home-assistant-js-websocket library. If that gets merged, I can connect with the option to ignore invalid certificates. Subscribe to this issue end get notified when there's a solution! :-)

**Comment by zenturacp** [comment]
I get the same error - But i have a real certificate signed from GlobalSign - i have no errors in Chrome or other where..

![Skærmbillede 2019-03-24 kl  20 37 50](https://user-images.githubusercontent.com/37262317/54884770-08f62500-4e75-11e9-8028-21b4500e5b34.png)

**Comment by roflcoopter** [comment]
Same error for me, im connecting locally over http
```
root INFO [hosted-plugin: 439] Reading HA Token from Environment Variables

root INFO [hosted-plugin: 439] Reading HA URL from Environment Variables

root INFO [hosted-plugin: 439] Connecting to Home Assistant...

root ERROR [hosted-plugin: 192] Error connecting to your Home Assistant Server at http://nuc:8123 and token 'eyJ0e...', check your network or update your VS Code Settings, make sure to (also) check your workspace settings! Error: ERR_CANNOT_CONNECT
```

**Comment by keesschollaart81** [comment]
Thanks for the info! The internal error is being swallowed by the same library (the PR contains a fix for that as well), hopefully this gets merged soon so you can all enjoy this extension...

**Comment by dpackham** [comment]
Does the pr above also fix the http connection. Issue I am having?   Nginx does ssl offload for me so I can use tts with my Google hub and Chromecast which requires http access to ha

**Comment by keesschollaart81** [comment]
About the HTTP connection issue, I',m not so sure I already know what's causing it (for HTTP with invalid certs I know). With this PR also comes some additional logging which hopefully gives info on what's wrong in your situation (@dpackham, @zenturacp @carstenschroeder).

While we're waiting, can one of you help? In this branch: https://github.com/keesschollaart81/vscode-home-assistant/tree/socket I copied/included some of the home-assistant-js-websocket's code. It should work with invalid certificates but also logs more info on the 'ERR_CANNOT_CONNECT'.

**Comment by txblue** [comment]
Is there a reason for NOT connecting config on the server via the hassio SHARE from Windows10 to hassio on RPi3. It appears to work

**Comment by roflcoopter** [comment]
> About the HTTP connection issue, I',m not so sure I already know what's causing it (for HTTP with invalid certs I know). With this PR also comes some additional logging which hopefully gives info on what's wrong in your situation (@dpackham, @zenturacp @carstenschroeder).
> 
> While we're waiting, can one of you help? In this branch: https://github.com/keesschollaart81/vscode-home-assistant/tree/socket I copied/included some of the home-assistant-js-websocket's code. It should work with invalid certificates but also logs more info on the 'ERR_CANNOT_CONNECT'.

Have you gotten any testers on this? 
I am using an IDE called Theia which wraps VSCode extensions inside it and to install extensions i point it towards the marketplace URL, so i need a URL which produces a ZIP file to be able to test this

**Comment by carstenschroeder** [comment]
I would also be happy to test, but I would need a VSX file or a hint how I can install from a github branch. Did not find any info on that...and I am new to vscode extension development.

**Comment by kstaniek** [comment]
+1 Have the same issue and using HTTP.

**Comment by keesschollaart81** [comment]
I'm in discussion with the guys maintaining the websocket library on how to get this fixed. Whatever comes out of that, I'll make sure this library works with insecure certificates by the end of the coming weekend.

**Comment by keesschollaart81** [comment]
I've introduced a new boolean setting: 'ignoreCertificates' which allows you to enable a connection with HA over an insecure transport / invalid certificates. It's unchecked by default. If someone now runs into a connection issue, an error is shown with a reason and the a hint to fix this via this setting.

I might update the internal implementation later when we agreed on how to deal with Node based WebSockets and error handling in the HA Websocket library but this will not change the users experience.

**Comment by naamah75** [comment]
Now all is working with the checkbox! Thanks!

**Comment by jgalak** [comment]
Is the checkbox meant to be used only when using http?  Or should it work with https as well?  I've got let's encrypt/DuckDNS running, so trying to connect via https with the following server string: `https://REDACTED.duckdns.org:8123/` but I still get:
`
Error connecting to your Home Assistant Server at https://REDACTED.duckdns.org:8123/ and token 'eyJ0e...', check your network or update your VS Code Settings, make sure to (also) check your workspace settings! Error: ERR_CANNOT_CONNECT`
and:
`Error in WebSocket connection: Unexpected server response: 404`

I'll note that this works perfectly for me in the Hass.io add-on VSC, but I'd really like it to work on the desktop install of VSC.

**Comment by jgalak** [comment]
I also tried using `http://REDACTEDLOCALIP:8123/` as the server string, and got the exact same result.

**Comment by jgalak** [comment]
Posted an issue, and just took it down.  In case anyone else falls into this trap:

In the Host URL setting, don't have a trailing `/` !

So it needs to be `https://REDACTED.duckdns.org` **not** `https://REDACTED.duckdns.org/`

This is implied by the explanatory text "...(no path or querystring)", but I missed it...

In conjunction with the aforementioned checkbox, it now works perfectly.  Thanks!

**Comment by cvladan** [comment]
C'mon guys :)
Please make a check and trim trailing slash if it is specified, or just some tooltip. Thanks @jgalak for writing his comment.

Just add in settings something like this: `(no path, querystring or trailing slash)`.
Proper config that works is:

![image](https://user-images.githubusercontent.com/1913156/58322978-e6579c80-7e22-11e9-8c4f-322d31f008f8.png)

**Comment by keesschollaart81** [comment]
I've updated the code so that it is less error prone, from now on, it will parse the URL and construct a new one from the scheme, host and port.

**Comment by frenck** [comment]
This will break stuff hosted in paths...
in this case Hass.io, which has the API under `/homeassistant/`...

**Comment by roopesh** [comment]
I'm having this problem today.  Switched from http to https and can't use the extension anymore.  I have 1.4.5, I clicked the checkbox but it didn't help.  I have a valid (Comodo) cert.  I've used the external address, hassio.local, and IP address.  All fail.  I generated a new token, still doesn't work.  I did validate the token using curl.

**Comment by Denyerec** [comment]
IDK if I'm unnecessarily resurrecting an issue or if it's a new manifestation of the same bug.

I'm getting "Error connecting to your Home Assistant Server at http://192.168.123.250:8123 and token 'DExc1...', check your network or update your VS Code Settings, make sure to (also) check your workspace settings! Error: ERR_INVALID_AUTH"  

Is there something that should be installed/running on the HA end to receive the connection - It's a vanilla install so far only running the Samba extension.
